Repository ie3-institute/pypsdm, pull requests merged in 2025-01, with the labels that each got.

#241 Fix node identifier for plot of voltage over a branch
  CHANGELOG.md
  docs/nbs/input_models.ipynb
  docs/nbs/plotting_utilities.ipynb
  docs/nbs/result_models.ipynb
  pypsdm/models/input/container/raw_grid.py
  pypsdm/plots/results/voltage.py
Labels: bug

#233 Allow python 3.12
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: enhancement, dependencies

#239 Fixed slack node identification if slack is not directly connected to…
  CHANGELOG.md
  pypsdm/models/input/container/raw_grid.py
Labels: bug

#246 Example Jupyter Notebook for enriching simbench networks with system participants
  nbs/enrich_simbench_grid.ipynb
  poetry.lock
  pypsdm/models/input/create/participants.py
Labels: documentation
